import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Add': 'Add',
        },
        'tr_TR': {
          'Search':'Ara',
          'Change\nLanguage':'   Dili\nDeğiştir',
          'Language':'Değiştir',
          ' Add': ' Ekle',
          'Refresh': '  Yenile ',
          'Show List ': '  Listele    ',
          'Activities Pages': 'Aktivite Sayfası ',
          'Activity : ': 'Aktivite : ',
          'Type : ': 'Tip : ',
          'Participants : ': 'Katılımcı : ',
          'Price : ': 'Ücret : ',
          'Key : ': 'Aktivite Numarası : ',
          'Accessibility : ': 'Ulaşılabilirlik : ',
          'Education': 'Eğitim',
          'Recreational': 'Eğlence',
          'Social': 'Sosyal',
          'Diy': 'Kendin Yap',
          'Charity': 'Yardım Etkinliği',
          'Cooking': 'Yemek Pişirme',
          'Relaxation': 'Dinlenme',
          'Music': 'Müzik',
          'Busywork': 'Yorucu İş',
          'Activities List': 'Aktivite Listesi',


          "Learn Express.js": 'Express.js öğren',
          "Learn to greet someone in a new language": 'Yeni bir dili iyi bir şekilde öğren',
          "Learn how to play a new sport": 'Yeni bir spor yapmayı öğren',
          "Text a friend you haven't talked to in a long time": 'Uzun zaman konuşmadığın bir arkadaş mesaj at',
          "Learn a new programming language": 'Yeni programlama dili öğren',
          "Learn how to fold a paper crane": 'Kağıt katlama sanatını öğren',
          "Find a DIY to do": 'Kendine yapacak bir şey bul',
          "Learn about the Golden Ratio": 'Altın oran hakkında bilgi edin',
          "Volunteer at a local animal shelter": 'Hayvan barınağına gönüllü ol',
          "Play a game of Monopoly": 'Monopoly oyna',
          "Bake pastries for you and your neighbor": 'Kendin ve komşun için yemek pişir',
          "Bake something you've never tried before": 'Denemediğin bir yemeği yapmaya çalış',
          "Take your dog on a walk": 'Köpeğinle yürüyüşe çık',
          "Meditate for five minutes": 'Beş dakika meditasyon yap',
          "Start a book you've never gotten around to reading": 'Hiç okumadığın bir kitaba başla',
          "Take a caffeine nap": 'Kafein şekerlemesi yap',
          "Take a bubble bath": 'Köpük banyosu yap',
          "Go to a nail salon": 'Manikür salonuna git',
          "Listen to your favorite album": 'Favori müzik albümünü dinle',
          "Learn to play a new instrument": 'Yeni müzik aletiş çalmayı öğren',
          "Teach your dog a new trick": 'Köpeğine yeni numaralar öğret',
          "Make a to-do list for your week": 'Kendine haftalık yapılacaklar listesi ekle ',
          "Go swimming with a friend": 'Arkadaşınla yüzmeye git',
          "Go on a long drive with no music": 'Müziksiz uzun sürüş yap',
          "Watch a movie you'd never usually watch": 'İzlemediğin bir filmi izle',
          "Go see a movie in theaters with a few friends": 'Arkadaşlarınla tiyatro izlemeye git',
          "Draw and color a Mandala": 'Mandala çiz ve boya',
          "Rearrange and organize your room": 'Odanı düzenle',
          "Pot some plants and put them around your house": 'Saksıda bitki yetiştirin',
          "Plan a vacation you've always wanted to take": 'Gitmek istediğin bir yer için plan yap',
          "Take your cat on a walk": 'Kedinle yürüyüşe çık',
          "Have a football scrimmage with some friends": 'Arkadaşlarınla futbol maçı yap',
          "Fill out a basketball bracket": 'Basketbol organizasyonu düzenle',
          "Play a game of tennis with a friend": 'Arkadaşınla tenis oyna',
          "Catch up with a friend over a lunch date": 'Bir öğlen yemeğini arkadaşınla ye',
          "Learn how to iceskate or rollerskate": 'Buz pateni ya da paten yapmayı öğren',
          "Go to a concert with local artists with some friends": 'Bazı arkadaşlarınla bir sanatçının konserine git',
          "Explore the nightlife of your city": 'Şehrindeki gece hayatını keşfet',
          "Fix something that's broken in your house": 'Evde kırılmış bir şeyi tamir et',
          "Wash your car": 'Arabanı yıka',
          "Find a charity and donate to it": 'Bir bağış kurumu bul ve bağış yap',
          "Hold a yard sale": 'Bahçe satışı yap',
          "Donate blood at a local blood center": 'Bir kan bağış merkezinde kan ver',
          "Shop at support your local farmers market": 'Çiftçi pazarından alışveriş yap',
          "Learn a new recipe": 'Yeni tarifler öğren',
          "Create a cookbook with your favorite recipes": 'Favori tafirlerini içeren kitap çıkar',
          "Create a compost pile": 'Bir yığın oluştur ? ? ',
          "Volunteer at your local food bank": 'Gıda bağışında bulun',
          "Create or update your resume": 'Özgeçmişi oluştur ve güncelle',
          "Paint the first thing you see": 'İlk gördüğün şeyi çiz',
          "Start a blog for something you're passionate about": 'Tutkun olan bir şeyi blog olarak yazmaya başla',
          "Start a garden": 'Bahçe kur',
          "Clean out your closet and donate the clothes you've outgrown": 'Dolabını temizle ve büyüdüğün kıyafetleri bağışla',
          "Catch up on world news": 'Yeni dünya haberlerini takip et',
          "Create a personal website": 'Kendi web siteni kur',
          "Listen to a new podcast": 'Yeni şarkılar dinle',
          "Have a paper airplane contest with some friends": 'Kağıttan uçak yarışması yap',
          "Learn calligraphy": 'Kaligrafi öğren',
          "Start a collection": 'Bir koleksiyon edin',
          "Go to a local thrift shop": 'İkinci el mağazayı ziyaret et',
          "Make a couch fort": ' ? ? ?? ',
          "Pick up litter around your favorite park": 'Favori parkının etrafındaki çöpleri topla',
          "Buy a new house decoration": 'Yeni ev dekorasyon aletleri al',
          "Write a thank you letter to an influential person in your life": 'Hayatındaki değerli birine teşekkür mektubu yaz',
          "Clean out your car": 'Arabanın dışını temizle',
          "Write a short story": 'Kısa bir hikaye yaz',
          "Do something nice for someone you care about": 'Değer verdiğin birine güzel bir şey yap',
          "Think of a new business idea": 'Yeni bir iş fikri düşün',
          "Clean out your garage": 'Garajını temizle',
          "Learn to sew on a button": 'Düğme dikmeyi öğrenin',
          "Learn how to french braid hair": 'Fransız saç örgülerini öğrenin',
          "Learn how to whistle with your fingers": 'Parmakla ıslık çalmayı öğren',
          "Learn to write with your nondominant hand": 'Kullanmadığın elinle yazı yazmayı öğren',
          "Make bread from scratch": 'Ekmek yapmayı dene',
          "Make a budget": 'Bütçe planı oluştur',
          "Learn how to write in shorthand": 'Stenografi öğren (Harfler ve sayılarla yazı yazma sanatı)',
          "Make a simple musical instrument": 'Basit bir müzik aleti yap',
          "Go to the gym": 'Spor salonuna git',
          "Try a food you don't like": 'Sevmediğin bir tadı dene',
          "Conquer one of your fears": 'Bir korkunu yen',
          "Go to a concert with some friends": 'Arkadaşlarınla konsere git',
          "Go to the library and find an interesting book": 'Kütüphaneye git ve ilginç kitap bul',
          "Go to an escape room": 'Kaçış odasına gid',
          "Go to a karaoke bar with some friends": 'Arkadaşlarınla karaoke partisine git',
          "Repaint a room in your house": 'Evdeki bir odayı tekrar boya',
          "Pull a harmless prank on one of your friends": 'Arkadaşlarından bir tanesine zarar vermeden eşek şakası yap',
          "Take a spontaneous road trip with some friends": 'Bazı arkadaşlarına rastgele bir rotada yolculuk yap',
          "Go stargazing": 'Yıldızları seyret',
          "Invite some friends over for a game night": 'Arkadaşlarını bir oyun gecesine davet et',
          "Make homemade ice cream": 'Evde dondurma yap',
          "Start a daily journal": 'Günlük geziye çık',
          "Go to a music festival with some friends": 'Bazı arkadaşlarınla müzik festivaline git',
          "Make a bucket list": 'Bir liste oluştur',
          "Binge watch a trending series": 'Gündemde olan bir dizi izle',
          "Learn how to make a website": 'Web sitesi yapmayı öğren',
          "Create and follow a savings plan": 'Tasarruf yap ve devam ettir',
          "Watch a classic movie": 'Klasik film izle',
          "Plan a trip to another country": 'Başka bir şehire yolculuk için plan yap',
          "Learn how the internet works": 'İnternetin nasıl çalıştığını öğren',
          "Take a hike at a local park": 'Parka yürüyüşe çık',
          "Make tie dye shirts": 'Kravat boya ?',
          "Make a scrapbook with pictures of your favorite memories": 'En sevdiğiniz anılarınızın resimlerini içeren bir karalama defteri yap',
          "Have a picnic with some friends": 'Bazı arkadaşlarınla pikniğe git',
          "Have a bonfire with your close friends": 'Yakın arkadaşlarınla şenlik ateşi yak',
          "Memorize the fifty states and their capitals": 'Elli eyaleti ve başkentlerini ezberle',
          "Take a class at your local community center that interests you": 'Yerel toplum merkezinizde ilginizi çeken bir ders al',
          "Resolve a problem you've been putting off": 'Ertelediğiniz bir sorunu çöz',
          "Make a new friend": 'Yeni arkadaş edin',
          "Learn origami": 'Origami öğren',
          "Learn how to use a french press": 'French press kullanmayı öğren',
          "Read a formal research paper on an interesting subject": 'İlginç bir konuyla ilgili resmi bir araştırma makalesini oku',
          "Listen to a new music genre": 'Yeni bir müzik türü dinle',
          "Volunteer at your local food pantry": 'Yerli malına gönüllü ol',
          "Learn how to make an Alexa skill": 'Alexa becerisini nasıl yapacağınızı öğren',
          "Surprise your significant other with something considerate": 'Karşınızdakini düşünceli bir şeyle şaşırt',
          "Learn Kotlin": 'Kotlin öğren',
          "Go for a run": 'Koşuya çık',
          "Learn woodworking": 'Ağaç işlemeyi öğren',
          "Start a band": 'Bir müzik grubu oluştur',
          "Cook something together with someone": 'Birisiyle yemek yap',
          "Have a jam session with your friends": '???',
          "Learn GraphQL": 'GraphQL öğren',
          "Play basketball with a group of friends": 'Bir grup arkadaşınla basketbol oyna',
          "Learn the Chinese erhu": 'Çince erhu müzik aletini öğren',
          "Start a webinar on a topic of your choice": 'Seçtiğiniz bir konuda bir web semineri başlat',
          "Learn how to use an Arduino": 'Ardunio nasıl kullanılır öğren',
          "Go see a Broadway production": 'Git bir Broadway prodüksiyonunu gör',
          "Learn Javascript": 'Javascript öğren',
          "Visit your past teachers": 'Eski öğretmenini ziyaret et',
          "Research a topic you're interested in": 'İlgi alanlarınla bir araştırma yap',
          "Listen to music you haven't heard in a while": 'Bu zamana kadar dinlemediğin bir müzik dinle',
          "Go on a fishing trip with some friends": 'Bazı arkadaşlarınla balığa çık',
          "Bake a pie with some friends": 'Arkadaşlarınla pasta pişir',
          "Do yoga": 'Yoga yap',
          "Visit a nearby museum": 'Yakında bir müze ziyaret et',
          "Have a photo session with some friends": 'Bazı arkadaşlarla bir fotoğraf seansı yap',
          "Watch the sunset or the sunrise": 'Gün doğumu ve ya batımını izle',
          "Play a volleyball match with some friends": 'Bazı arkadaşlarınla voleybol maçı yap',
          "Host a movie marathon with some friends": 'Bazı arkadaşlarınızla bir film maratonuna ev sahipliği yap',
          "Hold a video game tournament with some friends": 'Bazı arkadaşlarınızla bir video oyunu turnuvası düzenle',
          "Write a poem": 'Şiir yaz',
          "Take a nap": 'Kısa bir uyku çek',
          "Mow your lawn": 'Çimleri biç',
          "Practice coding in your favorite lanaguage": 'Favori programlama dilinde pratik yap',
          "Write a song": 'Şarkı yaz',
          "Play a video game": 'Oyun oyna',
          "Clean out your refrigerator": 'Buzdolabını temizle',
          "Study a foreign language": 'Yabancı dil çalış',
          "Learn the NATO phonetic alphabet": 'Nato fon alfabesini öğren  ',
          "Solve a Rubik's cube": 'Rubik küp çöz',
          "Make your own LEGO creation": 'Kendi LEGO tasarımınızı yap',
          "Plant a tree": 'Bir ağaç dik',
          "Contribute code or a monetary donation to an open-source software project": 'Açık kaynaklı bir yazılım projesine kod veya parasal bağışta bulun',
          "Uninstall unused apps from your devices": 'Kullanılmayan uygulamaları cihazlarınızdan kaldır',
          "Prepare a dish from a foreign culture": 'Yabancı bir kültürden bir yemek hazırla',
          "Patronize a local independent restaurant": 'Yerel bağımsız bir restoranı büyütün',
          "Give your pet ten minutes of focused attention": 'Evcil hayvanınıza on dakika odaklanın',
          "Explore a park you have never been to before": 'Daha önce hiç gitmediğiniz bir parkı keşfedin',
          "Configure two-factor authentication on your accounts": 'Hesaplarınızda iki faktörlü kimlik doğrulamayı yapılandır',
          "Create a meal plan for the coming week": 'Önümüzdeki hafta için bir yemek planı oluşturun',
          "Watch a Khan Academy lecture on a subject of your choosing":
              'Seçtiğiniz bir konuda Khan Academy dersini izle',
          "Shred old documents you don't need anymore": 'Artık ihtiyacınız olmayan eski belgeleri parçalayın',
          "Learn about a distributed version control system such as Git": 'Git  sistemi hakkında bilgi edin',
          "Write a note of appreciation to someone": 'Birine bir takdir notu yaz',
          "Draw something interesting": 'İlginç bir şey çiz',
          "Learn and play a new card game": 'Kart oyunları oynamayı öğren',
          "Write a list of things you are grateful for": 'Minnettar olduğunuz şeylerin bir listesini yazın',
          "Organize a bookshelf": 'Kitaplığını düzenle',
          "Organize a cluttered drawer": 'Dağınık bir çekmeceni düzenle',
          "Organize your music collection": 'Müzik listeni düzenle',
          "Organize your movie collection": 'Film listeni düzenle',
          "Learn Morse code": 'Mors alfabesini öğren',
          "Go for a walk": 'Yürüyüşe çık',
          "Mow your neighbor's lawn": 'Komşunuzun çimlerini biç',
          "Compliment someone": 'Birine iltifat et',
          "Draft your living will": 'Vasiyetini hazırla',
          "Prepare a 72-hour kit": '72 saatlik bir kit hazırla',
          "Color": 'Boyama yap',
          "Organize your pantry": 'Kilerinizi düzenle',
          "Back up important computer files": 'Önemli bilgisayar dosyalarını yedekle',
          "Memorize a favorite quote or poem": 'Favori bir alıntıyı veya şiiri ezberle',
          "Do something you used to do as a kid": 'Çocukken yaptığınız bir şeyi yap',
          "Organize your basement": 'Bodrumunuzu düzenle',
          "Sit in the dark and listen to your favorite music with no distractions": 'Karanlıkta otur ve en sevdiğin müziği dikkatiniz dağılmadan dinle',
          "Do a jigsaw puzzle": 'Yapboz yap',
          "Look at pictures and videos of cute animals": 'Sevimli hayvanların resimlerine ve videolarına bak',
          "Write a handwritten letter to somebody": 'Birine el yazısıyla yazılmış bir mektup yaz',
          "Match your storage containers with their lids": 'Saklama kaplarınızı kapaklarıyla eşleştir',
          "Start a family tree": 'Bir aile ağacı başlatın',
          "Look at your finances and find one way to save money": 'Mali durumunuza bakın ve tasarruf etmenin bir yolunu bul',
          "Organize your dresser": 'Şifonyerinizi düzenleyin',
          "Learn the periodic table": 'Periyodik tabloyu öğren',
          "Improve your touch typing": '10 parmak yazmayı geliştir',
          "Donate to your local food bank": 'Gıda bankasına bağış yap',
          "Learn how to beatbox": 'BeatBox yapmayı öğren',
        }
      };
}
