name: activity_app_with_getx
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  anim_search_bar: ^2.0.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  timezone: ^0.8.0
  analog_clock: ^0.1.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_keyboard_size: ^1.0.0+4
  translator: ^0.1.7


flutter:
  uses-material-design: true
  assets:
    - assets/image/123icon.png
    - assets/image/123icon.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0




